name: MS Teams Notification

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        # uses: jdcargile/ms-teams-notification@v1.3
        #teste 2
        uses: drsilva/teste@1.0.0
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: 'Novo PR em ${{github.repository}} em ${{github.head_ref}} para ${{github.base_ref}} link: <a href="https://github.com/${{github.repository}}/pull/${{ github.event.number }}">PR #${{ github.event.number }}</a> nome: ${{ github.event_name }}'
          notification-color: 17a2b8          
          timezone: America/Denver
